# Generated by Django 2.0.2 on 2018-02-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='param',
            field=models.IntegerField(null=True),
        ),
    ]
